version: '3.8'
services:

  devzone-db:
    image: postgres:10.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
